### ISSUE TITLE
GROUP BY error in Monthly Report page

### ISSUE THREAD

**Issue by DonatasStoncius** [LaravelDaily/Laraexpenses-QuickAdmin#1]
After installing and even after entering a few categories for each income categories and expenses categories and a few of incomes & expenses I get a GROUP BY error. I could solve the problem by adding ALL the columns to GROUP BY. No Laravel expert here, but something is wrong here.

Also the calculation of expenses is wrong, because the result from DB doesn't have a structure that is expected by the code, so removing the inner foreach cycle works and then it shows the Reports page.

**Comment by PovilasKorop** [comment]
@DonatasStoncius could you please add the exact error text? And maybe some more information about your data - just tried it myself and couldn't reproduce it. Works for me.

**Comment by DonatasStoncius** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/5501087/21293990/8e4389e8-c53b-11e6-891f-784ea75ee8d8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/5501087/21293991/8e6c8212-c53b-11e6-8580-3647ad705f3a.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/5501087/21293992/8e6f9b0a-c53b-11e6-8aed-5f9c92f5c8f7.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/5501087/21293993/8e839678-c53b-11e6-8949-b5940aef845a.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/5501087/21293994/8e83cc74-c53b-11e6-8ff7-bbd749e27662.png)
Added info that I entered to the project and the error message.
Running app with `php artisan serve`

Works with my code:
`<?php
namespace App\Http\Controllers;

use App\Income;
use App\Expense;
use Carbon\Carbon;
use Illuminate\Http\Request;

class MonthlyReportsController extends Controller
{
    public function index(Request $r)
    {
        $from    = Carbon::parse(sprintf(
            '%s-%s-01',
            $r->query('y', Carbon::now()->year),
            $r->query('m', Carbon::now()->month)
        ));
        $to      = clone $from;
        $to->day = $to->daysInMonth;

        $exp_q = Expense::with('expenses_category')
            ->whereBetween('entry_date', [$from, $to]);

        $inc_q = Income::with('income_category')
            ->whereBetween('entry_date', [$from, $to]);

        $exp_group = $exp_q->orderBy('amount', 'desc')->groupBy('expenses.expenses.id', 'expenses_category_id', 
		'expenses.expenses.entry_date', 'expenses.expenses.amount', 'expenses.expenses.created_at', 'expenses.expenses.updated_at', 'expenses.expenses.deleted_at')->get();
        $inc_group = $inc_q->orderBy('amount', 'desc')->groupBy('income_category_id', 'expenses.incomes.id', 'expenses.incomes.entry_date',
		'expenses.incomes.amount', 'expenses.incomes.created_at', 'expenses.incomes.updated_at', 'expenses.incomes.deleted_at'
		)->get();
        $exp_total = $exp_q->sum('amount');
        $inc_total = $inc_q->sum('amount');
        $profit    = $inc_total - $exp_total;

        $exp_summary = [];
        foreach ($exp_group as $exp) {
			if (!isset($exp_summary[$exp->expenses_category->name])) {
				$exp_summary[$exp->expenses_category->name] = [
					'name'   => $exp->expenses_category->name,
					'amount' => 0,
				];
			}
			$exp_summary[$exp->expenses_category->name]['amount'] += $exp->amount;
        }

        $inc_summary = [];
        foreach ($inc_group as $inc) {
			if (!isset($inc_summary[$inc->income_category->name])) {
				$inc_summary[$inc->income_category->name] = [
					'name'   => $inc->income_category->name,
					'amount' => 0,
				];
			}
			$inc_summary[$inc->income_category->name]['amount'] += $inc->amount;
        }

        return view('monthly_reports.index', compact(
            'exp_summary',
            'inc_summary',
            'exp_total',
            'inc_total',
            'profit'
        ));
    }
}`

**Comment by PovilasKorop** [comment]
@DonatasStoncius apparently, this error depends on your server settings.

> Your server probably has ONLY_FULL_GROUP_BY turned on. You can either turn it off or add each of your selected fields to the group by.

See here: [http://stackoverflow.com/questions/1244169/mysql-1140-mixing-of-group-columns](http://stackoverflow.com/questions/1244169/mysql-1140-mixing-of-group-columns)

**Comment by DonatasStoncius** [comment]
Oh, ok. Never had that happen to me. Thanks for the answer.
